INSERT INTO PERSON(ID,NAME,LOCATION,BIRTH_DATE )
VALUES(10001, 'ba','Hyderabad',sysdate());

INSERT INTO PERSON(ID, NAME,LOCATION, BIRTH_DATE )
VALUES(10002, 'sow','New Yk', sysdate());

INSERT INTO PERSON(ID, NAME, LOCATION, BIRTH_DATE )
VALUES(10003, 'ba','Hyderabad',sysdate());